export const SCREENER_CONFIG = {
  MOMENTUM_WEIGHT: 0.3,
  VOLUME_WEIGHT: 0.2,
  LIQUIDITY_WEIGHT: 0.25,
  VOLATILITY_WEIGHT: 0.1,
  BREAKOUT_WEIGHT: 0.15,

  MOMENTUM_CLAMP_PCT: 5,
  MOMENTUM_STRONG_PCT: 1.5,
  MOMENTUM_MODERATE_PCT: 0.5,

  VOLUME_LOW_MAX: 0.5,
  VOLUME_NORMAL_MAX: 1,
  VOLUME_ELEVATED_MAX: 2,
  VOLUME_SCORE_CLAMP: 3,

  VOLATILITY_LOW_MAX: 0.5,
  VOLATILITY_NORMAL_MAX: 2,
  VOLATILITY_HIGH_MAX: 5,
  VOLATILITY_IDEAL_PCT: 2,
  VOLATILITY_SCORE_SPREAD: 4,

  LIQUIDITY_HIGH_MIN_VOLUME: 5_000_000,
  LIQUIDITY_MEDIUM_MIN_VOLUME: 500_000,
  LIQUIDITY_HIGH_MAX_SPREAD_PCT: 0.1,
  LIQUIDITY_MEDIUM_MAX_SPREAD_PCT: 0.3,
  LIQUIDITY_MAX_ACCEPTABLE_SPREAD_PCT: 1,
  LIQUIDITY_VOLUME_SCALE: 100_000_000,

  BREAKOUT_PROXIMITY_PCT: 1.5,
  BREAKOUT_MIN_VOLUME_RATIO: 1.2,

  EXHAUSTION_MOMENTUM_PCT: 4,
  EXHAUSTION_VOLUME_RATIO: 3,
  EXHAUSTION_DEVIATION_PCT: 5,
  EXHAUSTION_VOLATILITY_PCT: 5,
  EXHAUSTION_MIN_FLAGS: 2,

  PENALTY_LOW_LIQUIDITY: 15,
  PENALTY_HIGH_SPREAD: 10,
  PENALTY_LOW_VOLUME: 10,
  PENALTY_EXTREME_VOLATILITY: 10,
  PENALTY_POSSIBLE_EXHAUSTION: 10,

  MIN_VALID_VOLUME_USDT: 10_000,
  CANDLE_UNIVERSE_LIMIT: 40,
  CANDLE_COUNT: 20,
  CONCURRENCY_LIMIT: 8,
  CANDLE_FETCH_TIMEOUT_MS: 5000,
  CANDLE_FETCH_RETRIES: 1,

  SCREENER_CACHE_TTL_MS: 20000,
};
