export const AI_CONFIG = {
  SCORE_WEIGHTS: {
    screener: 0.15,
    technical: 0.30,
    momentum: 0.10,
    structure: 0.15,
    breakout: 0.10,
    liquidity: 0.10,
    volatility: 0.10,
  },
  SCORE_THRESHOLDS: { STRONG: 80, MODERATE: 70, WEAK: 60 },

  CONFIDENCE_BASE: 70,
  CONFIDENCE_CONFLICT_PENALTY: 15,
  CONFIDENCE_PARTIAL_DATA_PENALTY: 15,
  CONFIDENCE_MULTI_TF_LOW_PENALTY: 10,
  CONFIDENCE_MULTI_TF_HIGH_BONUS: 10,
  CONFIDENCE_MISMATCH_PENALTY: 20,
  CONFIDENCE_MIN: 0,
  CONFIDENCE_MAX: 100,

  MIN_SCORE_FOR_TRADE: 60,
  MIN_CONFIDENCE_FOR_TRADE: 50,

  EXHAUSTION_RSI_HIGH: 70,
  EXHAUSTION_RSI_LOW: 30,
  EXHAUSTION_DEVIATION_PCT: 5,
  EXHAUSTION_VOLUME_RATIO: 3,
  EXHAUSTION_ATR_PCT: 5,
  EXHAUSTION_MIN_FLAGS: 2,

  BREAKOUT_MIN_VOLUME_RATIO: 1.5,

  ENTRY_ZONE_PCT: 0.5,

  MARKET_REGIME_CACHE_TTL_MS: 60000,
};
