export function buildSnapshot({ technical, screener, riskPlan, marketRegime, aiScore, confidence }) {
  return {
    price: technical.price,
    rsi: technical.indicators.rsi,
    macd: technical.indicators.macd,
    ema: technical.indicators.ema,
    atr: technical.indicators.atr,
    atrPercent: technical.indicators.atrPercent,
    adx: technical.indicators.adx,
    volume: technical.indicators.volume,
    marketStructure: technical.structure.marketStructure,
    support: technical.support,
    resistance: technical.resistance,
    breakoutStatus: technical.breakout.status,
    screenerScore: screener?.screenerScore ?? null,
    technicalScore: technical.technicalScore,
    riskScore: riskPlan?.riskScore ?? null,
    marketRegime: marketRegime.regime,
    funding: riskPlan?.funding ?? null,
    openInterest: riskPlan?.openInterest ?? null,
    aiScore,
    confidence,
    capturedAt: Date.now(),
  };
}
